"""FastAPI router for local video ingestion and asynchronous media preparation."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status
from fastapi.responses import FileResponse

from .media import (
    FFmpegUnavailable,
    LocalMediaService,
    MediaJobService,
    MediaProcessingError,
    SQLAlchemyClipRepository,
    object_value,
    public_clip,
)


def _http_error(exc: Exception) -> HTTPException:
    if isinstance(exc, FFmpegUnavailable):
        return HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=str(exc))
    return HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc))


def _get_clip_or_404(repository: Any, clip_id: str) -> Any:
    model = getattr(repository, "clip_model", None)
    session = getattr(repository, "session", None)
    if model is None or session is None:
        raise HTTPException(status_code=501, detail="This repository does not support lookup by id.")
    clip = session.query(model).filter(model.id == clip_id).first()
    if clip is None:
        raise HTTPException(status_code=404, detail="Clip not found.")
    return clip


def _evidence_frames(clip: Any) -> list[dict[str, Any]]:
    frames = object_value(clip, "keyframes", "keyframe_data")
    if not frames:
        analyses = getattr(clip, "analyses", None) or []
        # Most recent adaptive extraction is the evidence generated by this
        # pipeline; other analyses may be model-understanding records.
        candidates = [entry for entry in analyses if object_value(entry, "mode") == "adaptive_frames"]
        selected = candidates[-1] if candidates else None
        frames = object_value(selected, "evidence_frames", default=[]) if selected else []
    if isinstance(frames, str):
        import json
        try:
            frames = json.loads(frames)
        except json.JSONDecodeError:
            frames = []
    return frames if isinstance(frames, list) else []


def _thumbnail_path(clip: Any) -> str | None:
    path = object_value(clip, "thumbnail_path")
    if path:
        return str(path)
    analyses = getattr(clip, "analyses", None) or []
    candidates = [entry for entry in analyses if object_value(entry, "mode") == "adaptive_frames"]
    tags = object_value(candidates[-1], "tags", default={}) if candidates else {}
    return str(tags.get("thumbnail_path")) if isinstance(tags, dict) and tags.get("thumbnail_path") else None


def create_media_router(
    media_service: LocalMediaService,
    job_service: MediaJobService,
    *,
    get_repository: Callable[[], Any] | None = None,
) -> APIRouter:
    """Create routes bound to a media service.

    ``get_repository`` should be a per-request factory for SQLAlchemy apps.  If
    omitted, the service's repository is used (appropriate for a single session
    local prototype).  A production app should create it with its session
    dependency; see ``attach_media_router`` below.
    """
    router = APIRouter(prefix="/api/media", tags=["media"])

    def repository() -> Any:
        return get_repository() if get_repository else media_service.repository

    def queue_processing(service: LocalMediaService, clip_id: str | int) -> Any:
        """Run with a fresh Session in the pool thread when the adapter supports it."""
        def work(progress: Callable[[int, str], None]) -> dict[str, Any]:
            worker = service.worker_copy()
            try:
                clip = worker.get_clip(clip_id)
                if clip is None:
                    # In-memory test repositories have no lookup API; they are
                    # intentionally handled by the caller-provided service.
                    raise MediaProcessingError("Clip could not be reloaded for background processing.")
                return worker.process_clip(clip, progress)
            finally:
                worker.close()
        return job_service.submit(clip_id, work)

    @router.get("/health")
    def media_health() -> dict[str, Any]:
        try:
            return {"available": True, "binaries": media_service.check_binaries()}
        except FFmpegUnavailable as exc:
            return {"available": False, "error": str(exc)}

    @router.post("/imports", status_code=status.HTTP_202_ACCEPTED)
    async def import_video(file: UploadFile = File(...)) -> dict[str, Any]:
        if not (file.filename or "").strip():
            raise HTTPException(status_code=422, detail="A filename is required.")
        # Starlette streams the multipart part into a spooled temp file, so using
        # ``file.file`` here avoids reading multi-GB source videos into RAM.
        service = media_service if get_repository is None else LocalMediaService(
            media_service.root, repository(), ffmpeg_bin=media_service.ffmpeg_bin,
            ffprobe_bin=media_service.ffprobe_bin, max_upload_bytes=media_service.max_upload_bytes,
        )
        try:
            clip, duplicate = service.import_upload(file.file, file.filename, file.content_type)
        except (MediaProcessingError, OSError) as exc:
            raise _http_error(exc) from exc
        finally:
            await file.close()
        if duplicate:
            return {"duplicate": True, "clip": public_clip(clip), "job": None}
        clip_id = object_value(clip, "id", "clip_id")
        if service.get_clip(clip_id) is None:
            # Useful for intentionally simple repository implementations; the
            # SQLAlchemy adapter takes the fresh-session branch above.
            job = job_service.submit(clip_id, lambda progress: service.process_clip(clip, progress))
        else:
            job = queue_processing(service, clip_id)
        return {"duplicate": False, "clip": public_clip(clip), "job": job.to_dict()}

    @router.post("/clips/{clip_id}/process", status_code=status.HTTP_202_ACCEPTED)
    def reprocess_clip(clip_id: str) -> dict[str, Any]:
        repo = repository()
        clip = _get_clip_or_404(repo, clip_id)
        service = media_service if get_repository is None else LocalMediaService(
            media_service.root, repo, ffmpeg_bin=media_service.ffmpeg_bin,
            ffprobe_bin=media_service.ffprobe_bin, max_upload_bytes=media_service.max_upload_bytes,
        )
        if service.get_clip(clip_id) is None:
            job = job_service.submit(clip_id, lambda progress: service.process_clip(clip, progress))
        else:
            job = queue_processing(service, clip_id)
        return {"job": job.to_dict()}

    @router.get("/jobs/{job_id}")
    def get_job(job_id: str) -> dict[str, Any]:
        job = job_service.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="Media job not found.")
        return job.to_dict()

    @router.get("/clips/{clip_id}")
    def get_clip(clip_id: str) -> dict[str, Any]:
        clip = _get_clip_or_404(repository(), clip_id)
        payload = public_clip(clip)
        payload["keyframes"] = _evidence_frames(clip)
        return payload

    @router.get("/clips/{clip_id}/thumbnail")
    def get_thumbnail(clip_id: str) -> FileResponse:
        clip = _get_clip_or_404(repository(), clip_id)
        path = _thumbnail_path(clip)
        if not path or not Path(path).is_file():
            raise HTTPException(status_code=404, detail="Thumbnail has not been generated yet.")
        return FileResponse(path, media_type="image/png" if str(path).lower().endswith(".png") else "image/jpeg")

    @router.get("/clips/{clip_id}/frames/{frame_index}")
    def get_evidence_frame(clip_id: str, frame_index: int) -> FileResponse:
        clip = _get_clip_or_404(repository(), clip_id)
        frames = _evidence_frames(clip)
        if frame_index < 0 or frame_index >= len(frames):
            raise HTTPException(status_code=404, detail="Evidence frame not found.")
        path = frames[frame_index].get("path") if isinstance(frames[frame_index], dict) else None
        if not path or not Path(path).is_file():
            raise HTTPException(status_code=404, detail="Evidence frame file no longer exists.")
        return FileResponse(path, media_type="image/png" if str(path).lower().endswith(".png") else "image/jpeg")

    return router


def attach_media_router(
    app: Any,
    *,
    storage_root: str | Path,
    clip_model: type[Any],
    get_db: Callable[[], Any],
    max_workers: int = 2,
) -> None:
    """Convenience integration for a conventional FastAPI + SQLAlchemy app.

    Example::

        attach_media_router(app, storage_root="data/media", clip_model=Clip, get_db=get_db)

    ``get_db`` is the application's normal FastAPI dependency generator.  The
    router opens a short-lived DB session for each request.  Background workers
    must not reuse request sessions, so the import endpoint retains the Clip
    object only for this V1 implementation; processors update it with the same
    repository instance.  For multi-process deployment, replace MediaJobService
    with a durable queue and create a fresh repository in its worker.
    """
    # FastAPI resolves generator dependencies correctly only at route declaration
    # time.  This wrapper creates/reclaims the session around each repository use.
    # Most V1 apps use SessionLocal directly; accepting it here keeps the module
    # independent from the eventual database.py name.
    def factory() -> SQLAlchemyClipRepository:
        db_dependency = get_db()
        if hasattr(db_dependency, "__next__"):
            session = next(db_dependency)
            # We deliberately don't close here: the app's get_db generator owns
            # cleanup in normal routes. For direct SessionLocal pass a lambda that
            # returns a session instead.
        else:
            session = db_dependency
        return SQLAlchemyClipRepository(session, clip_model)

    bootstrap = factory()
    service = LocalMediaService(storage_root, bootstrap)
    jobs = MediaJobService(max_workers=max_workers)
    app.include_router(create_media_router(service, jobs, get_repository=factory))
