import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { api, Clip, ModelConfig, Pattern, Render } from './api'
import { Activity, ArrowUpRight, BarChart3, Check, ChevronRight, Clapperboard, CloudUpload, Database, FileVideo, FolderOpen, Gauge, LayoutDashboard, Lightbulb, LoaderCircle, MoreHorizontal, Play, Plus, Search, Settings2, Sparkles, Upload, WandSparkles, X } from 'lucide-react'

type Page = '工作台' | '素材库' | '标签审核' | '混剪工作台' | '成片管理' | '数据回传' | '规律分析' | '模型与接口'
type Notice = { text: string; error?: boolean } | null
const nav: { label: Page; icon: typeof LayoutDashboard }[] = [
  { label: '工作台', icon: LayoutDashboard }, { label: '素材库', icon: FolderOpen }, { label: '标签审核', icon: Check }, { label: '混剪工作台', icon: Clapperboard }, { label: '成片管理', icon: FileVideo }, { label: '数据回传', icon: Upload }, { label: '规律分析', icon: BarChart3 }, { label: '模型与接口', icon: Settings2 },
]

function clipImage(id: string) { return `/api/media/clips/${id}/thumbnail` }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '—' }
function duration(value?: number | null) { return value == null ? '处理中' : `${value.toFixed(1)} 秒` }
function roleLabel(role: string) { return ({ head: '头部', middle: '中部', tail: '尾部' } as Record<string, string>)[role] ?? role }
function errorText(error: unknown) { return error instanceof Error ? error.message : '操作失败，请稍后重试。' }

function StatusDot({ color = 'green' }: { color?: string }) { return <span className={`status-dot ${color}`} /> }
function Loading() { return <div className="empty-panel"><LoaderCircle className="spin" size={26}/><p>正在读取本地数据…</p></div> }
function Empty({ children }: { children: React.ReactNode }) { return <div className="empty-panel"><FileVideo size={32}/><h2>还没有可显示的内容</h2><p>{children}</p></div> }

function Sidebar({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  return <aside className="sidebar"><div className="brand"><div className="brand-mark"><span/><span/><span/></div><span>CUTLINE</span></div><div className="project-switch"><div className="project-avatar">C</div><div><b>CUTLINE</b><small>本地短视频实验室</small></div></div><nav>{nav.map(({ label, icon: Icon }) => <button key={label} className={page === label ? 'nav-item active' : 'nav-item'} onClick={() => setPage(label)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="sidebar-footer"><div className="usage"><span>Local-first / V1</span><div className="progress"><i/></div></div></div></aside>
}

function Topbar({ page, onImport }: { page: Page; onImport: () => void }) { return <header className="topbar"><div className="crumb"><span>CUTLINE</span><ChevronRight size={14}/><b>{page}</b></div><div className="top-actions"><button className="icon-button" title="本地模式"><Activity size={18}/></button><button className="import-button" onClick={onImport}><Plus size={16}/> 导入素材</button></div></header> }

function ClipThumb({ clip, small = false }: { clip: Clip; small?: boolean }) {
  return <div className={`real-thumb ${small ? 'small' : ''}`}><img src={clipImage(clip.id)} alt={clip.filename} onError={event => { event.currentTarget.style.display = 'none' }}/><FileVideo size={small ? 15 : 26}/></div>
}

function Dashboard({ clips, renders, loading, go }: { clips: Clip[]; renders: Render[]; loading: boolean; go: (page: Page) => void }) {
  const pending = clips.filter(c => c.review_status !== 'approved')
  const completed = renders.filter(r => r.status === 'completed')
  return <main className="main dashboard"><section className="hero"><div><p className="eyebrow"><span/> LOCAL WORKFLOW</p><h1>从素材到成片，<br/><i>跑通真实实验。</i></h1><p className="hero-copy">所有数据均来自本地 API；先导入和审核素材，再创建可追溯的混剪实验。</p><button className="primary" onClick={() => go('混剪工作台')}><WandSparkles size={17}/> 创建实验 <ArrowUpRight size={16}/></button></div><div className="signal-card"><div className="signal-top"><span>当前状态</span><Activity size={16}/></div><strong>{clips.length}<small> 条</small></strong><p>已导入素材<br/>{completed.length} 条成片已导出</p><div className="signal-bars">{[32, 48, 40, 68, 52, 84, 76].map((n, i) => <i key={i} style={{ height: n }}/>)}</div></div></section><section className="metrics">{[{ label: '素材总数', value: clips.length, note: `${pending.length} 条待审核`, icon: Database }, { label: '已审核素材', value: clips.filter(c => c.review_status === 'approved').length, note: '可进入混剪', icon: Check }, { label: '成片数量', value: renders.length, note: `${completed.length} 条已完成`, icon: FileVideo }, { label: '待处理素材', value: clips.filter(c => !c.usable_range).length, note: '等待抽帧或理解', icon: Sparkles }].map(metric => <article className="metric" key={metric.label}><div className="metric-top"><span>{metric.label}</span><metric.icon size={17}/></div><b>{loading ? '—' : metric.value}</b><small><StatusDot/>{metric.note}</small></article>)}</section><section className="split-section"><div className="recent"><div className="section-title"><div><p className="eyebrow">最近素材</p><h2>真实媒体库</h2></div><button className="text-button" onClick={() => go('素材库')}>查看素材库 <ArrowUpRight size={14}/></button></div>{clips.length ? <div className="clip-list">{clips.slice(0, 4).map(clip => <div className="clip-row" key={clip.id}><ClipThumb clip={clip} small/><div className="clip-name"><b>{clip.filename}</b><span>{clip.id.slice(0, 8)} · {clip.dish ?? '未标注菜品'}</span></div><span className="role">{roleLabel(clip.segment_role)}</span><span className="confidence">{clip.review_status === 'approved' ? '已通过' : '待审核'}</span></div>)}</div> : <Empty>通过右上角“导入素材”加入第一个视频。</Empty>}</div><aside className="insight"><div className="eyebrow"><span/> WORKFLOW</div><h3>下一步</h3><p>{pending.length ? `有 ${pending.length} 条素材等待审核。审核通过后才能生成成片。` : clips.length ? '素材已审核，可以在混剪工作台创建实验。' : '导入视频后，系统会自动读取媒体信息、抽取关键帧。'}</p><button className="outline" onClick={() => go(pending.length ? '标签审核' : '混剪工作台')}>继续工作 <ChevronRight size={14}/></button></aside></section></main>
}

function Library({ clips, loading, reload }: { clips: Clip[]; loading: boolean; reload: () => void }) {
  const [query, setQuery] = useState(''); const [dish, setDish] = useState('全部')
  const dishes = useMemo(() => Array.from(new Set(clips.map(c => c.dish).filter(Boolean) as string[])), [clips])
  const visible = clips.filter(c => (!query || `${c.filename} ${c.dish ?? ''} ${JSON.stringify(c.tags)}`.toLowerCase().includes(query.toLowerCase())) && (dish === '全部' || c.dish === dish))
  return <main className="main library"><div className="page-heading"><div><p className="eyebrow">MEDIA ARCHIVE / LIVE</p><h1>素材库</h1></div><button className="outline" onClick={reload}><Activity size={16}/> 刷新</button></div><div className="filterbar"><div className="search"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索文件名、菜品或标签"/></div>{['全部', ...dishes].map(item => <button onClick={() => setDish(item)} className={dish === item ? 'selected' : ''} key={item}>{item}</button>)}<span className="result-count">显示 {visible.length} 条</span></div>{loading ? <Loading/> : visible.length ? <div className="library-grid">{visible.map(clip => <article className="media-card" key={clip.id}><div className="media-frame"><ClipThumb clip={clip}/><span className="duration">{clip.usable_range ? `${clip.usable_range.end - clip.usable_range.start}s` : '处理中'}</span></div><div className="media-info"><div><span className="clipid">{clip.id.slice(0, 8)}</span><h3>{clip.filename}</h3></div><button title="刷新详情" onClick={reload}><MoreHorizontal size={17}/></button></div><div className="media-foot"><span className="role-pill">{roleLabel(clip.segment_role)}</span><i>{clip.dish ?? '未标注菜品'}</i><span className="media-score">{clip.review_status === 'approved' ? '已审核' : '待审核'}</span></div></article>)}</div> : <Empty>没有符合筛选条件的素材。</Empty>}</main>
}

function Review({ clips, loading, reload, notice }: { clips: Clip[]; loading: boolean; reload: () => void; notice: (value: Notice) => void }) {
  const queue = clips.filter(c => c.review_status !== 'rejected'); const [index, setIndex] = useState(0); const clip = queue[Math.min(index, Math.max(queue.length - 1, 0))]
  const [dish, setDish] = useState(''); const [role, setRole] = useState('middle'); const [submitting, setSubmitting] = useState(false); const [analyzing, setAnalyzing] = useState(false)
  useEffect(() => { if (clip) { setDish(clip.dish ?? ''); setRole(['head', 'middle', 'tail'].includes(clip.segment_role) ? clip.segment_role : 'middle') } }, [clip?.id, clip?.dish, clip?.segment_role])
  const submit = async (status: 'approved' | 'rejected') => { if (!clip) return; if (status === 'approved' && !dish.trim()) { notice({ text: '请填写菜品，混剪时需要同菜品校验。', error: true }); return } setSubmitting(true); try { await api.approveClip(clip.id, { status, updates: { dish: dish.trim(), segment_role: role, usable_range: clip.usable_range ?? undefined } }); notice({ text: status === 'approved' ? '标签已确认，素材可以进入混剪。' : '素材已驳回。' }); setIndex(0); reload() } catch (error) { notice({ text: errorText(error), error: true }) } finally { setSubmitting(false) } }
  const analyze = async () => { if (!clip) return; setAnalyzing(true); try { await api.analyzeClip(clip.id); notice({ text: '已让小米直接理解视频并生成画面描述。' }); reload() } catch (error) { notice({ text: errorText(error), error: true }) } finally { setAnalyzing(false) } }
  if (loading) return <main className="main review"><Loading/></main>
  if (!clip) return <main className="main review"><div className="page-heading"><div><p className="eyebrow">REVIEW QUEUE</p><h1>标签审核</h1></div></div><Empty>没有可审核素材。可先导入一个视频。</Empty></main>
  const tags = Object.entries(clip.tags).filter(([key]) => key !== 'thumbnail_path')
  return <main className="main review"><div className="page-heading"><div><p className="eyebrow">REVIEW QUEUE / {queue.length}</p><h1>标签审核</h1></div><div className="review-progress"><span>{index + 1} / {queue.length}</span><div><i style={{ width: `${((index + 1) / queue.length) * 100}%` }}/></div></div></div><div className="review-layout"><section className="review-video"><div className="review-real-image"><ClipThumb clip={clip}/></div><div className="video-controls"><Play size={17}/><span>审核素材：{clip.filename}</span></div></section><section className="tag-panel"><div className="tag-panel-head"><div><span className="clipid">{clip.id}</span><h2>{clip.filename}</h2></div></div><div className="summary-box"><p>模型摘要</p><b>{clip.summary ?? '暂无模型摘要，可点击下方按钮让小米直接理解视频。'}</b><button className="outline analyze-button" disabled={analyzing} onClick={analyze}><Sparkles size={15}/>{analyzing ? '小米正在理解视频…' : (clip.summary ? '重新分析' : '智能分析（小米直接理解视频）')}</button></div><div className="edit-fields"><label>菜品<input value={dish} onChange={e => setDish(e.target.value)} placeholder="例如：烤鱼"/></label><label>片段角色<select value={role} onChange={e => setRole(e.target.value)}><option value="head">头部</option><option value="middle">中部</option><option value="tail">尾部</option></select></label></div><div className="tags-area"><div className="tag-group"><span>模型标签</span><div>{tags.length ? tags.map(([key, value]) => <button key={key} type="button">{key}: {Array.isArray(value) ? value.join('、') : String(value)}</button>) : <small>暂无结构化标签</small>}</div></div><div className="tag-group"><span>可用区间</span><div><button type="button">{clip.usable_range ? `${clip.usable_range.start}s — ${clip.usable_range.end}s` : '等待处理'}</button></div></div></div><div className="review-actions"><button className="reject" disabled={submitting} onClick={() => submit('rejected')}><X size={16}/> 驳回</button><button className="approve" disabled={submitting} onClick={() => submit('approved')}><Check size={16}/> {submitting ? '保存中…' : '确认标签'}</button></div>{queue.length > 1 && <button className="text-button review-next" onClick={() => setIndex((index + 1) % queue.length)}>跳过，查看下一条 <ChevronRight size={14}/></button>}</section></div></main>
}

function MixLab({ clips, reload, notice }: { clips: Clip[]; reload: () => void; notice: (value: Notice) => void }) {
  const approved = clips.filter(c => c.review_status === 'approved' && c.usable_range); const [selected, setSelected] = useState<string[]>([]); const [name, setName] = useState(''); const [dish, setDish] = useState(''); const [count, setCount] = useState(1); const [working, setWorking] = useState(false)
  const validSelected = approved.filter(c => selected.includes(c.id)); const choices = Array.from(new Set(approved.map(c => c.dish).filter(Boolean) as string[]))
  useEffect(() => { if (!dish && choices.length) setDish(choices[0]) }, [choices.join('|')])
  const estimate = validSelected.reduce((total, clip) => total + ((clip.usable_range?.end ?? 0) - (clip.usable_range?.start ?? 0)), 0)
  const create = async () => { if (!name.trim() || !dish.trim() || !validSelected.length) { notice({ text: '请填写实验名称、选择菜品和至少一条已审核素材。', error: true }); return } const base: { clip_id: string; start: number; end: number }[] = []; let total = 0; const source = validSelected.filter(c => !c.dish || c.dish === dish); if (!source.length) { notice({ text: '所选素材与菜品不一致。', error: true }); return } let i = 0; while (total < 10) { const clip = source[i % source.length]; const range = clip.usable_range!; base.push({ clip_id: clip.id, start: range.start, end: range.end }); total += range.end - range.start; i += 1; if (i > 30) break } if (total > 15.5) { notice({ text: `当前组合约 ${total.toFixed(1)} 秒，超过 15 秒上限，请选择更短的素材。`, error: true }); return } setWorking(true); try { const result = await api.createExperiment({ name: name.trim(), dish, target_duration_seconds: total, generation_count: count, variables: { selected_clip_ids: selected }, variants: Array.from({ length: count }, (_, index) => ({ name: `${name.trim()}-${String(index + 1).padStart(2, '0')}`, clips: base, values: { variant: index + 1 } })) }); for (const render of result.renders) await api.runRender(render.id); notice({ text: `已创建并完成导出 ${result.renders.length} 条成片。` }); reload() } catch (error) { notice({ text: errorText(error), error: true }) } finally { setWorking(false) } }
  return <main className="main mix"><div className="page-heading"><div><p className="eyebrow">CONTROLLED EXPERIMENT</p><h1>混剪工作台</h1></div><span className="experiment-status"><StatusDot color="gold"/> 使用审核通过的真实素材</span></div><div className="mix-layout"><section className="mix-config"><div className="section-title"><div><p className="eyebrow">01 / 实验定义</p><h2>创建成片</h2></div></div><label>实验名称<input value={name} onChange={e => setName(e.target.value)} placeholder="例如：火焰开场测试"/></label><label>菜品<select value={dish} onChange={e => setDish(e.target.value)}><option value="">选择菜品</option>{choices.map(item => <option key={item}>{item}</option>)}</select></label><div className="quantity"><span>生成数量</span><div><button onClick={() => setCount(Math.max(1, count - 1))}>−</button><b>{count}</b><button onClick={() => setCount(Math.min(10, count + 1))}>+</button></div></div><button className="primary full" disabled={working || !approved.length} onClick={create}><WandSparkles size={17}/>{working ? '正在导出…' : `生成 ${count} 条实验成片`}</button></section><section className="timeline-area"><div className="timeline-head"><div><p className="eyebrow">02 / 选择素材</p><h2>已审核素材 <span>预计 {estimate.toFixed(1)} 秒（系统会循环至至少 10 秒）</span></h2></div></div>{approved.length ? <div className="selectable-clips">{approved.map(clip => <label className={selected.includes(clip.id) ? 'selected-clip active' : 'selected-clip'} key={clip.id}><input type="checkbox" checked={selected.includes(clip.id)} onChange={() => setSelected(current => current.includes(clip.id) ? current.filter(id => id !== clip.id) : [...current, clip.id])}/><ClipThumb clip={clip} small/><span><b>{clip.filename}</b><small>{clip.dish ?? '未标注'} · {duration((clip.usable_range!.end - clip.usable_range!.start))}</small></span></label>)}</div> : <Empty>还没有可用素材。先到“标签审核”确认至少一条素材。</Empty>}<div className="timeline-footer"><span><Check size={15}/> 创建时将执行同菜品、时长与审核状态校验</span></div></section></div></main>
}

function Finished({ renders, loading, reload, notice }: { renders: Render[]; loading: boolean; reload: () => void; notice: (value: Notice) => void }) {
  const run = async (render: Render) => { try { await api.runRender(render.id); notice({ text: '成片已导出。' }); reload() } catch (error) { notice({ text: errorText(error), error: true }) } }
  return <main className="main"><div className="page-heading"><div><p className="eyebrow">RENDER ARCHIVE / LIVE</p><h1>成片管理</h1></div><button className="outline" onClick={reload}><Activity size={16}/> 刷新</button></div>{loading ? <Loading/> : renders.length ? <div className="render-list">{renders.map(render => <article className="render-card" key={render.id}><div><span className="clipid">{render.video_id}</span><h2>{render.title ?? '未命名成片'}</h2><p>{render.dish} · {duration(render.duration_seconds)} · 创建于 {formatDate(render.created_at)}</p></div><span className={`render-status ${render.status}`}>{render.status === 'completed' ? '已完成' : render.status === 'queued' ? '待导出' : render.status}</span><div className="render-actions">{render.status === 'completed' ? <a className="outline" href={api.renderDownloadUrl(render.id)}>下载 MP4</a> : <button className="primary" onClick={() => run(render)}>执行导出</button>}</div></article>)}</div> : <Empty>在混剪工作台创建实验后，导出的成片会出现在这里。</Empty>}</main>
}

function DataReturn({ renders, notice }: { renders: Render[]; notice: (value: Notice) => void }) { const input = useRef<HTMLInputElement>(null); const [working, setWorking] = useState(false); const importFile = async (file?: File) => { if (!file) return; setWorking(true); try { const result = await api.metrics(file) as { imported?: number; updated?: number; errors?: string[] }; notice({ text: `数据已导入：新增 ${result.imported ?? 0} 条，更新 ${result.updated ?? 0} 条。${result.errors?.length ? ` ${result.errors.length} 行未导入。` : ''}` }) } catch (error) { notice({ text: errorText(error), error: true }) } finally { setWorking(false) } }; return <main className="main"><div className="page-heading"><div><p className="eyebrow">PLATFORM SIGNALS</p><h1>数据回传</h1></div></div><div className="data-grid"><section className="upload-zone"><CloudUpload size={30}/><h2>导入平台 CSV</h2><p>上传抖音导出的 CSV；系统使用 <code>video_id</code> 自动匹配这里的成片。</p><button className="outline" disabled={working} onClick={() => input.current?.click()}>{working ? '导入中…' : '选择 CSV 文件'}</button><input ref={input} hidden type="file" accept=".csv,text/csv" onChange={(e: ChangeEvent<HTMLInputElement>) => importFile(e.target.files?.[0])}/><small>只支持 .csv · 单次最多 20MB</small></section><section className="return-side"><div className="section-title"><div><p className="eyebrow">可回传视频 ID</p><h2>{renders.length} 条成片</h2></div></div>{renders.length ? renders.slice(0, 8).map(render => <div className="return-item" key={render.id}><div className="return-num">{render.video_id}</div><div><b>{render.title ?? '未命名成片'}</b><span>{render.status === 'completed' ? '已导出，可用于平台数据匹配' : '等待导出完成'}</span></div></div>) : <p className="muted-copy">暂无成片。先创建并导出实验成片。</p>}</section></div></main> }

function Analysis({ notice }: { notice: (value: Notice) => void }) { const [data, setData] = useState<{ sample_size: number; global_score: number | null; patterns: Pattern[]; message?: string } | null>(null); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); try { setData(await api.patterns()) } catch (error) { notice({ text: errorText(error), error: true }) } finally { setLoading(false) } }, [notice]); useEffect(() => { void load() }, [load]); return <main className="main analysis"><div className="page-heading"><div><p className="eyebrow">LEARNING LOOP / LIVE</p><h1>规律分析</h1></div><button className="outline" onClick={load}><Activity size={16}/> 刷新分析</button></div>{loading ? <Loading/> : !data?.patterns.length ? <Empty>{data?.message ?? '暂无符合分析条件的数据；平台数据需在发布后至少 72 小时且播放量不低于 500。'}</Empty> : <><div className="analysis-hero"><div><span className="pill verified"><Check size={13}/> 基于真实回传数据</span><h2>当前有效样本<br/><i>{data.sample_size} 条。</i></h2><p>综合评分 {data.global_score?.toFixed(4) ?? '—'}。规律状态由独立实验数量和样本量自动判定。</p></div></div><div className="pattern-table"><div className="section-title"><div><p className="eyebrow">观察结果</p><h2>候选与已验证规律</h2></div></div>{data.patterns.map((pattern, index) => <div className="pattern-row" key={`${pattern.dimension}${pattern.value}`}><span className="rank">{String(index + 1).padStart(2, '0')}</span><b>{pattern.dimension}：{pattern.value}</b><span className="category">{pattern.status}</span><strong>{pattern.relative_lift >= 0 ? '+' : ''}{(pattern.relative_lift * 100).toFixed(1)}%</strong><div className="mini-confidence"><i style={{ width: `${pattern.confidence * 100}%` }}/></div><span>{Math.round(pattern.confidence * 100)}%</span></div>)}</div></>}</main> }

function Models({ notice }: { notice: (value: Notice) => void }) { const [configs, setConfigs] = useState<ModelConfig[]>([]); const [open, setOpen] = useState(false); const [geminiOpen, setGeminiOpen] = useState(false); const [mimoOpen, setMimoOpen] = useState(false); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); try { setConfigs(await api.modelConfigs()) } catch (error) { notice({ text: errorText(error), error: true }) } finally { setLoading(false) } }, [notice]); useEffect(() => { void load() }, [load]); const test = async (config: ModelConfig) => { try { const result = await api.testModelConfig(config.id); notice({ text: `${config.name}：${result.detail}（${result.latency_ms}ms）`, error: !result.ok }); load() } catch (error) { notice({ text: errorText(error), error: true }) } }; return <main className="main models"><div className="page-heading"><div><p className="eyebrow">MODEL ROUTING / SECURE VAULT</p><h1>模型与接口</h1></div><div className="model-actions"><button className="outline" onClick={() => setMimoOpen(true)}><Sparkles size={16}/> 添加 MiMo 视频</button><button className="outline" onClick={() => setGeminiOpen(true)}><Sparkles size={16}/> 添加 Gemini 3</button><button className="primary" onClick={() => setOpen(true)}><Plus size={16}/> 添加通用模型</button></div></div>{loading ? <Loading/> : configs.length ? <div className="model-cards">{configs.map(config => <section className="model-card" key={config.id}><div className="model-head"><div className="model-logo">◎</div><div><span className="pill">{config.is_default ? '默认配置' : config.provider}</span><h2>{config.name}</h2><p>{config.model_name} · {config.api_key_masked}</p></div></div><div className="model-stats"><div><span>图片理解</span><b>{config.supports_images ? '已启用' : '未启用'}</b></div><div><span>原生视频+音轨</span><b className="muted">{config.supports_native_video ? '已启用' : '未启用'}</b></div><div><span>状态</span><b>{config.is_active ? '可用' : '已停用'}</b></div></div>{['gemini', 'mimo'].includes(config.protocol) && <p className="muted-copy">{config.protocol === 'mimo' ? 'MiMo' : 'Gemini'} 原生媒体上限：{Math.round(config.max_native_media_bytes / 1024 / 1024)} MB</p>}{config.last_error && <p className="error-copy">最近错误：{config.last_error}</p>}<div className="model-actions"><button onClick={() => test(config)}><Gauge size={15}/> 测试连接</button><span>{config.base_url}</span></div></section>)}</div> : <Empty>尚未配置模型。添加后，可对导入素材执行模型理解。</Empty>}{open && <ModelModal close={() => setOpen(false)} reload={load} notice={notice}/>} {geminiOpen && <GeminiModelModal close={() => setGeminiOpen(false)} reload={load} notice={notice}/>} {mimoOpen && <MimoModelModal close={() => setMimoOpen(false)} reload={load} notice={notice}/>}</main> }

function ModelModal({ close, reload, notice }: { close: () => void; reload: () => void; notice: (value: Notice) => void }) { const [working, setWorking] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setWorking(true); try { await api.createModelConfig({ name: form.get('name'), provider: 'OpenAI-compatible', protocol: 'openai', base_url: form.get('base_url'), api_key: form.get('api_key'), model_name: form.get('model_name'), supports_images: true, supports_structured_json: true, is_default: form.get('is_default') === 'on' }); notice({ text: '模型配置已安全保存。' }); close(); reload() } catch (error) { notice({ text: errorText(error), error: true }) } finally { setWorking(false) } }; return <div className="modal-backdrop"><form className="modal config-form" onSubmit={submit}><button className="close" type="button" onClick={close}><X size={18}/></button><p className="eyebrow">MODEL CONFIGURATION</p><h2>添加模型配置</h2><label>显示名称<input name="name" required placeholder="例如：OpenAI Vision"/></label><label>Base URL<input name="base_url" required type="url" placeholder="https://api.openai.com/v1"/></label><label>模型名称<input name="model_name" required placeholder="例如：gpt-4o"/></label><label>API Key<input name="api_key" required type="password" autoComplete="new-password"/></label><label className="check-label"><input name="is_default" type="checkbox"/> 设为默认素材理解模型</label><button className="primary full" disabled={working}>{working ? '保存中…' : '安全保存配置'}</button></form></div> }

function GeminiModelModal({ close, reload, notice }: { close: () => void; reload: () => void; notice: (value: Notice) => void }) { const [working, setWorking] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const limitMb = Number(form.get('max_native_media_mb')); if (!Number.isFinite(limitMb) || limitMb < 1) { notice({ text: '原生媒体大小上限必须至少为 1 MB。', error: true }); return } setWorking(true); try { await api.createModelConfig({ name: form.get('name'), provider: '兔子 API', protocol: 'gemini', base_url: 'https://api.tu-zi.com', api_key: form.get('api_key'), model_name: 'gemini-3-flash-preview', supports_images: true, supports_native_video: true, supports_structured_json: true, max_native_media_bytes: Math.round(limitMb * 1024 * 1024), is_default: form.get('is_default') === 'on' }); notice({ text: 'Gemini 3 原生视频配置已安全保存。' }); close(); reload() } catch (error) { notice({ text: errorText(error), error: true }) } finally { setWorking(false) } }; return <div className="modal-backdrop"><form className="modal config-form" onSubmit={submit}><button className="close" type="button" onClick={close}><X size={18}/></button><p className="eyebrow">TUZI API / GEMINI NATIVE</p><h2>添加 Gemini 3 原生视频</h2><label>显示名称<input name="name" required defaultValue="兔子 API Gemini 3 Flash"/></label><label>Base URL<input value="https://api.tu-zi.com" readOnly/></label><label>模型名称<input value="gemini-3-flash-preview" readOnly/></label><label>API Key<input name="api_key" required type="password" autoComplete="new-password"/></label><label>原生媒体大小上限（MB）<input name="max_native_media_mb" required type="number" min="1" step="1" defaultValue="100"/></label><p className="modal-note">将原始视频和内嵌音轨直接发送至 Gemini；“测试连接”仅验证模型列表，不调用推理。</p><label className="check-label"><input name="is_default" type="checkbox"/> 设为默认素材理解模型</label><button className="primary full" disabled={working}>{working ? '保存中…' : '安全保存 Gemini 配置'}</button></form></div> }

function MimoModelModal({ close, reload, notice }: { close: () => void; reload: () => void; notice: (value: Notice) => void }) { const [working, setWorking] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const limitMb = Number(form.get('max_native_media_mb')); if (!Number.isFinite(limitMb) || limitMb < 1 || limitMb > 37) { notice({ text: 'MiMo 原始视频上限必须为 1–37 MB，以满足 50 MB Base64 请求限制。', error: true }); return } setWorking(true); try { await api.createModelConfig({ name: form.get('name'), provider: '小米 MiMo Token Plan', protocol: 'mimo', base_url: 'https://token-plan-cn.xiaomimimo.com/v1', api_key: form.get('api_key'), model_name: form.get('model_name'), supports_images: true, supports_native_video: true, supports_structured_json: true, max_native_media_bytes: Math.round(limitMb * 1024 * 1024), is_default: form.get('is_default') === 'on' }); notice({ text: 'MiMo 原生视频配置已安全保存。' }); close(); reload() } catch (error) { notice({ text: errorText(error), error: true }) } finally { setWorking(false) } }; return <div className="modal-backdrop"><form className="modal config-form" onSubmit={submit}><button className="close" type="button" onClick={close}><X size={18}/></button><p className="eyebrow">XIAOMI MIMO / NATIVE VIDEO</p><h2>添加 MiMo 原生视频</h2><label>显示名称<input name="name" required defaultValue="小米 MiMo V2.5 原生视频"/></label><label>Base URL<input value="https://token-plan-cn.xiaomimimo.com/v1" readOnly/></label><label>模型名称<input name="model_name" required defaultValue="mimo-v2.5"/></label><label>API Key<input name="api_key" required type="password" autoComplete="new-password"/></label><label>原始视频大小上限（MB）<input name="max_native_media_mb" required type="number" min="1" max="37" step="1" defaultValue="37"/></label><p className="modal-note">完整视频与内嵌音轨将以 Base64 视频请求发送给 MiMo；默认模型为官方视频理解支持的 mimo-v2.5。“测试连接”仅验证模型列表，不调用推理。</p><label className="check-label"><input name="is_default" type="checkbox"/> 设为默认素材理解模型</label><button className="primary full" disabled={working}>{working ? '保存中…' : '安全保存 MiMo 配置'}</button></form></div> }

function ImportModal({ close, reload, notice }: { close: () => void; reload: () => void; notice: (value: Notice) => void }) { const input = useRef<HTMLInputElement>(null); const [state, setState] = useState('导入后会自动去重、读取媒体信息并生成关键帧。'); const submit = async (file?: File) => { if (!file) return; setState(`正在导入 ${file.name}…`); try { await api.upload(file); setState('已进入处理队列。稍后刷新素材库即可查看。'); notice({ text: '素材已进入处理队列。' }); reload() } catch (error) { setState(`导入失败：${errorText(error)}`) } }; return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={close}><X size={18}/></button><p className="eyebrow">IMPORT MEDIA</p><h2>导入新素材</h2><div className="dropzone" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); submit(event.dataTransfer.files[0]) }}><CloudUpload size={30}/><b>拖入视频文件</b><span>或从电脑选择 · MP4 / MOV / M4V</span><button className="outline" onClick={() => input.current?.click()}>选择文件</button><input ref={input} type="file" accept="video/*" hidden onChange={event => submit(event.target.files?.[0])}/></div><div className="modal-note"><Sparkles size={15}/><span>{state}</span></div></div></div> }

export default function App() { const [page, setPage] = useState<Page>('工作台'); const [clips, setClips] = useState<Clip[]>([]); const [renders, setRenders] = useState<Render[]>([]); const [loading, setLoading] = useState(true); const [importOpen, setImportOpen] = useState(false); const [notice, setNotice] = useState<Notice>(null); const showNotice = useCallback((value: Notice) => { setNotice(value); if (value) window.setTimeout(() => setNotice(null), 5000) }, []); const reload = useCallback(async () => { setLoading(true); try { const [clipData, renderData] = await Promise.all([api.clips(), api.renders()]); setClips(clipData); setRenders(renderData) } catch (error) { showNotice({ text: `无法读取本地 API：${errorText(error)}`, error: true }) } finally { setLoading(false) } }, [showNotice]); useEffect(() => { void reload() }, [reload]); const view = page === '工作台' ? <Dashboard clips={clips} renders={renders} loading={loading} go={setPage}/> : page === '素材库' ? <Library clips={clips} loading={loading} reload={reload}/> : page === '标签审核' ? <Review clips={clips} loading={loading} reload={reload} notice={showNotice}/> : page === '混剪工作台' ? <MixLab clips={clips} reload={reload} notice={showNotice}/> : page === '成片管理' ? <Finished renders={renders} loading={loading} reload={reload} notice={showNotice}/> : page === '数据回传' ? <DataReturn renders={renders} notice={showNotice}/> : page === '规律分析' ? <Analysis notice={showNotice}/> : <Models notice={showNotice}/>; return <div className="app-shell"><Sidebar page={page} setPage={setPage}/><div className="content"><Topbar page={page} onImport={() => setImportOpen(true)}/>{view}</div>{importOpen && <ImportModal close={() => setImportOpen(false)} reload={reload} notice={showNotice}/>} {notice && <div className={notice.error ? 'toast error' : 'toast'}>{notice.text}</div>}</div> }
